[package]
name = "oxipng"
version = "0.8.0"
authors = ["Joshua Holmer <jholmer.in@gmail.com>"]
description = "A lossless PNG compression optimizer"
license = "MIT"
documentation = "https://shssoichiro.github.io/oxipng/"
homepage = "https://github.com/shssoichiro/oxipng"
repository = "https://github.com/shssoichiro/oxipng"
exclude = [
  "tests/*",
  "bench/*",
]

[lib]
name = "oxipng"
path = "src/lib.rs"

[[bin]]
name = "oxipng"
path = "src/main.rs"
doc = false

[dependencies]
bit-vec = "^0.4.2"
byteorder = "^0.5.0"
clap = "^2.2.5"
crc = "^1.2.0"
libc = "^0.2.4"
libz-sys = "^1.0.0"
miniz-sys = "^0.1.7"
num_cpus = "^0.2.11"
regex = "^0.1.63"
scoped-pool = "^0.1.8"

[dev-dependencies.image]
version = "^0.8.0"
default-features = false
features = ["png_codec"]
