[package]
name = "optipng"
version = "2.0.0-alpha.1"
authors = ["Joshua Holmer <jholmer.in@gmail.com>"]

[dependencies]
byteorder = "^0.4.0"
clap = "^1.5.4"
crc = "^1.0.0"
libc = "^0.2.4"
libz-sys = "^1.0.0"
regex = "^0.1.8"
