[package]
name = "oxipng"
version = "1.0.0-alpha.1"
authors = ["Joshua Holmer <jholmer.in@gmail.com>"]

[dependencies]
bit-vec = "^0.4.2"
byteorder = "^0.4.0"
clap = "^1.5.4"
crc = "^1.0.0"
crossbeam = "^0.2.1"
libc = "^0.2.4"
libz-sys = "^1.0.0"
regex = "^0.1.8"

[dev-dependencies]
image = "^0.6.1"
