name: deploy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: olegtarasov/get-tag@v2
      id: tagName
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Build oxipng
      run: |
        cargo build --release
        strip target/release/oxipng.exe
    - name: Create zip
      run: |
        $OXIPNG_PATH="$Env:GITHUB_WORKSPACE\target\release"
        7z a oxipng-${{ steps.tagName.outputs.tag }}-x86_64-pc-windows-msvc.zip "$OXIPNG_PATH\oxipng.exe"
    - name: Create a release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ steps.tagName.outputs.tag }}
        files: |
          oxipng-${{ steps.tagName.outputs.tag }}-x86_64-pc-windows-msvc.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
